import type { KeynoteStep } from '../types/keynote'

// Phase 2 uses restrained demonstration copy only. Later phases should replace
// these content objects without changing the controller or renderer contract.
export const KEYNOTE_STEPS: KeynoteStep[] = [
  {
    id: 'opening-title',
    chapterId: 'opening',
    chapterNumber: 0,
    stageNumber: 1,
    title: '1984 Blue Ocean',
    renderer: 'title',
    typographyTheme: 'opening',
    visualTheme: 'opening',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'sailboats',
    ariaLabel: 'Opening title for 1984 Blue Ocean',
    presenterNote: 'Final opening narration will be added in a later phase.',
    chapterStart: true,
    content: {
      renderer: 'title',
      eyebrow: 'A Jack OS Keynote',
      title: '1984 Blue Ocean',
      subtitle: 'Bridging Strategy and Execution',
      body: 'A presentation framework for the story still to come.',
    },
  },
  {
    id: 'opening-premise',
    chapterId: 'opening',
    chapterNumber: 0,
    stageNumber: 2,
    title: 'A Working Thesis',
    renderer: 'image-text',
    typographyTheme: 'opening',
    visualTheme: 'opening',
    transition: 'image',
    transitionScope: 'build',
    buildMode: 'accumulate',
    imageAssetId: 'school-of-fish',
    ariaLabel: 'Opening premise with ocean photography and placeholder summary',
    presenterNote: 'Placeholder premise only; not final keynote copy.',
    chapterEnd: true,
    content: {
      renderer: 'image-text',
      headline: 'A calmer way to connect ideas, systems, and outcomes.',
      body: 'This placeholder stage demonstrates the image-and-text layout that later chapters will use.',
      layout: 'image-right',
    },
  },
  {
    id: 'technical-divide-contrast',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 1,
    title: 'Business and Technical Teams',
    renderer: 'split',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'slide',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Comparison of business and technical perspectives',
    presenterNote: 'Demonstrates split-stage comparison without final claims.',
    chapterStart: true,
    content: {
      renderer: 'split',
      summary: 'The same problem can look different from each side of the room.',
      leftTitle: 'Business View',
      leftBody: 'Priorities often start with timing, cost, risk, and the outcome a decision is meant to create.',
      rightTitle: 'Technical View',
      rightBody: 'Implementation often starts with constraints, dependencies, data, and the tradeoffs behind a system.',
    },
  },
  {
    id: 'technical-divide-map',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 2,
    title: 'Translation Layer',
    renderer: 'diagram',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Diagram showing strategy, systems, and communication as a translation layer',
    presenterNote: 'Diagram labels are placeholders for later story content.',
    chapterEnd: true,
    content: {
      renderer: 'diagram',
      title: 'A shared language reduces guesswork.',
      summary: 'This demo diagram shows how a chapter can organize typed relationship data without owning navigation.',
      items: [
        {
          label: 'Strategy',
          description: 'What the organization is trying to make true.',
        },
        {
          label: 'Systems',
          description: 'How the work is actually represented, shipped, and measured.',
        },
        {
          label: 'Communication',
          description: 'The layer that keeps intent and execution aligned.',
        },
      ],
    },
  },
  {
    id: 'financial-friction-metric',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 1,
    title: 'Friction Compounds',
    renderer: 'metric',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'sharks',
    ariaLabel: 'Metric-style placeholder about operational friction',
    presenterNote: 'No fabricated statistic is used; final numbers require approval.',
    chapterStart: true,
    content: {
      renderer: 'metric',
      value: 'Friction',
      label: 'Costs compound when teams translate too late.',
      body: 'This metric stage supports large values and tabular numerals without baking data into the component.',
    },
  },
  {
    id: 'financial-friction-note',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 2,
    title: 'Cost of Delay',
    renderer: 'quote',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Quote-style placeholder about cost of delay',
    presenterNote: 'Quote stage is structural scaffolding only.',
    chapterEnd: true,
    content: {
      renderer: 'quote',
      quote: 'Every handoff asks the work to explain itself again.',
      attribution: 'Placeholder chapter note',
      body: 'Future content can replace this with a concise approved thesis.',
    },
  },
  {
    id: 'blue-ocean-photography',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 1,
    title: 'The Blue Ocean Mindset',
    renderer: 'image-text',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'image',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'sunlight',
    ariaLabel: 'Blue Ocean Mindset image stage with sunlight over water',
    presenterNote: 'Demonstrates photographic editorial chapter treatment.',
    chapterStart: true,
    content: {
      renderer: 'image-text',
      headline: 'Look for the water no one is fighting over yet.',
      body: 'This placeholder stage reserves room for the strategic core of the keynote.',
      layout: 'image-background',
    },
  },
  {
    id: 'blue-ocean-positioning',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 2,
    title: 'Positioning',
    renderer: 'split',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Split stage comparing competition and clarity',
    presenterNote: 'Second split stage checks accumulated build behavior.',
    chapterEnd: true,
    content: {
      renderer: 'split',
      summary: 'A better frame can change the shape of the problem.',
      leftTitle: 'Crowded Waters',
      leftBody: 'Teams compete inside inherited assumptions and familiar constraints.',
      rightTitle: 'Clearer Waters',
      rightBody: 'The work becomes easier to judge when the value, audience, and tradeoffs are explicit.',
    },
  },
  {
    id: 'living-proof-terminal',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 1,
    title: 'The Living Proof',
    renderer: 'terminal',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'reveal',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Terminal-style placeholder showing Jack OS as a working system',
    presenterNote: 'Avoids fake hacking; frames Jack OS as implementation evidence.',
    chapterStart: true,
    content: {
      renderer: 'terminal',
      title: 'A portfolio that behaves like a system.',
      lines: [
        'jack-os> open 1984-blue-ocean',
        'window-manager: focus established',
        'presentation-engine: typed registry loaded',
        'assets: staged on demand',
        'status: ready for final narrative',
      ],
    },
  },
  {
    id: 'living-proof-timeline',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 2,
    title: 'System Evolution',
    renderer: 'timeline',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Timeline placeholder showing the Jack OS evolution pattern',
    presenterNote: 'Milestones remain concise and replaceable.',
    chapterEnd: true,
    content: {
      renderer: 'timeline',
      title: 'Jack OS evolves through deliberate releases.',
      milestones: [
        {
          label: 'V1',
          title: 'Public Portfolio',
          description: 'The desktop identity becomes the primary navigation model.',
        },
        {
          label: 'V2',
          title: 'Interactive OS',
          description: 'Applications, personalization, sound, search, and system behavior mature.',
        },
        {
          label: 'V3',
          title: 'Flagship Keynote',
          description: 'The portfolio gains a structured presentation environment.',
        },
      ],
    },
  },
  {
    id: 'simplicity-image',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 1,
    title: 'Simplicity is Sophistication',
    renderer: 'image-text',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'ocean-floor',
    ariaLabel: 'Minimal image stage with ocean floor photography',
    presenterNote: 'Final manifesto copy comes later.',
    chapterStart: true,
    content: {
      renderer: 'image-text',
      headline: 'The clearest interface is the one that knows what to leave out.',
      body: 'This final chapter placeholder demonstrates a quieter visual register.',
      layout: 'image-left',
    },
  },
  {
    id: 'simplicity-closing',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 2,
    title: 'Complete',
    renderer: 'quote',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Closing placeholder indicating the presentation is complete',
    presenterNote: 'Marks the end of the Phase 2 demonstration deck.',
    chapterEnd: true,
    content: {
      renderer: 'quote',
      quote: 'End of Phase 2 shell.',
      attribution: 'Ready for final chapter content',
      body: 'The engine, visual system, and reusable storytelling components are now in place.',
    },
  },
]

export function getKeynoteStepById(stepId: string) {
  return KEYNOTE_STEPS.find((step) => step.id === stepId)
}

export function getKeynoteStepIndexById(stepId: string) {
  return KEYNOTE_STEPS.findIndex((step) => step.id === stepId)
}
