import type { KeynoteStep } from '../types/keynote'

export const KEYNOTE_STEPS: KeynoteStep[] = [
  {
    id: 'opening-working-thesis',
    chapterId: 'opening',
    chapterNumber: 0,
    stageNumber: 1,
    title: 'Working Thesis',
    renderer: 'image-text',
    typographyTheme: 'opening',
    visualTheme: 'opening',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'school-of-fish',
    ariaLabel: 'Working thesis introducing the bridge between strategy and execution',
    presenterNote: 'Open the argument before mentioning Jack personally.',
    chapterStart: true,
    chapterEnd: true,
    content: {
      renderer: 'image-text',
      headline: 'The future belongs to people who can bridge worlds.',
      secondaryLine: 'The bridge between strategy and execution is where meaningful products begin.',
      body: 'Business strategy defines what must change. Technology determines what can be built. Real progress begins when both sides understand the same problem.',
      layout: 'image-right',
    },
  },
  {
    id: 'technical-divide-symptom',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 1,
    title: 'The Symptom',
    renderer: 'diagram',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'slide',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Diagram showing investment, technical projects, a break in alignment, and expected outcomes',
    presenterNote: 'Diagnose the problem without blaming either side.',
    chapterStart: true,
    content: {
      renderer: 'diagram',
      title: 'Organizations invest in technology. Projects still miss the outcome.',
      summary: 'Companies adopt AI, cloud platforms, security systems, and new software expecting speed and efficiency. Many initiatives stall because the problem was never understood the same way by everyone involved.',
      variant: 'flow',
      items: [
        {
          label: 'Investment',
          description: 'The organization commits budget, time, attention, and expectation.',
        },
        {
          label: 'Technical Project',
          description: 'Teams begin building systems, tools, automations, and controls.',
        },
        {
          label: 'Alignment Break',
          description: 'The intended outcome and the implementation path drift apart.',
        },
        {
          label: 'Expected Outcome',
          description: 'The business result becomes harder to reach, measure, or explain.',
        },
      ],
    },
  },
  {
    id: 'technical-divide-business-mind',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 2,
    title: 'The Business Mind',
    renderer: 'diagram',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Business-side decision lens listing revenue, margins, timing, risk, customer impact, and competitive position',
    presenterNote: 'Validate the business lens as practical and necessary.',
    content: {
      renderer: 'diagram',
      title: 'The business side begins with the outcome.',
      summary: 'Business leaders often evaluate decisions through cost, market timing, risk exposure, customer experience, and measurable return. They need confidence that the technical work supports the intended result.',
      variant: 'grid',
      items: [
        { label: 'Revenue', description: 'Will this create, protect, or clarify value?' },
        { label: 'Margins', description: 'How does the work affect cost and efficiency?' },
        { label: 'Timing', description: 'When does the opportunity matter most?' },
        { label: 'Risk', description: 'What exposure comes with the decision?' },
        { label: 'Customer Impact', description: 'How does the change affect real people?' },
        { label: 'Position', description: 'Does the work improve competitive clarity?' },
      ],
    },
  },
  {
    id: 'technical-divide-technical-mind',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 3,
    title: 'The Technical Mind',
    renderer: 'diagram',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Technical-side decision lens listing architecture, dependencies, data, performance, security, and maintainability',
    presenterNote: 'Frame technical thinking as disciplined execution, not detachment.',
    content: {
      renderer: 'diagram',
      title: 'The technical side begins with the system.',
      summary: 'Technical teams evaluate constraints, system design, scalability, reliability, security, and implementation tradeoffs. Their responsibility is to turn an objective into something functional and sustainable.',
      variant: 'grid',
      items: [
        { label: 'Architecture', description: 'How should the system be structured?' },
        { label: 'Dependencies', description: 'What does the work rely on?' },
        { label: 'Data', description: 'What information must be trusted and moved?' },
        { label: 'Performance', description: 'How does the system behave under pressure?' },
        { label: 'Security', description: 'What needs to be protected?' },
        { label: 'Maintainability', description: 'Can the result be supported over time?' },
      ],
    },
  },
  {
    id: 'technical-divide-translation-gap',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 4,
    title: 'The Translation Gap',
    renderer: 'split',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Split view comparing business outcomes and technical reliability with translation between them',
    presenterNote: 'This is Chapter 1’s bridge moment.',
    content: {
      renderer: 'split',
      summary: 'The same problem can look different from each side of the room.',
      leftTitle: 'Business View',
      leftBody: 'What outcome must this decision create?',
      rightTitle: 'Technical View',
      rightBody: 'What system can reliably produce that outcome?',
      bridgeLabel: 'Translation',
      closingLine: 'When the shared language disappears, intelligent teams can still move in different directions.',
    },
  },
  {
    id: 'technical-divide-shared-mission',
    chapterId: 'technical-divide',
    chapterNumber: 1,
    stageNumber: 5,
    title: 'The Shared Mission',
    renderer: 'title',
    typographyTheme: 'technical',
    visualTheme: 'technical-divide',
    transition: 'fade',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Chapter 1 conclusion explaining the shared mission between business and technical teams',
    presenterNote: 'Transition toward the financial cost when understanding arrives late.',
    chapterEnd: true,
    content: {
      renderer: 'title',
      eyebrow: 'THE SHARED MISSION',
      title: 'The goal is not to choose a side.',
      subtitle: 'The goal is to make both sides understand the same mission.',
      body: 'Business context gives technical work direction. Technical understanding gives strategy realism. Strong execution begins when each side respects the constraints, priorities, and language of the other.',
      closingLine: 'Understanding comes before architecture.',
    },
  },
  {
    id: 'financial-friction-cfo-check',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 1,
    title: 'The CFO’s Reality Check',
    renderer: 'diagram',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Flow from technical decision to operational effect to financial consequence',
    presenterNote: 'Translate friction into business terms without inventing numbers.',
    chapterStart: true,
    content: {
      renderer: 'diagram',
      title: 'Every technical decision eventually reaches the ledger.',
      summary: 'A delayed feature, oversized cloud environment, unclear requirement, or poorly prioritized security control may begin as a technical issue. It ends as lost time, higher operating cost, missed opportunity, or increased exposure.',
      variant: 'flow',
      items: [
        { label: 'Technical Decision', description: 'A choice about systems, scope, architecture, or controls.' },
        { label: 'Operational Effect', description: 'The choice changes time, workflow, reliability, or exposure.' },
        { label: 'Financial Consequence', description: 'The effect reaches cost, opportunity, risk, or customer value.' },
      ],
    },
  },
  {
    id: 'financial-friction-delayed-launches',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 2,
    title: 'Delayed Launches',
    renderer: 'timeline',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Timeline showing planned launch, rework, and delayed release',
    presenterNote: 'Keep this grounded in market timing, not invented losses.',
    content: {
      renderer: 'timeline',
      title: 'Delay has a market cost.',
      milestones: [
        {
          label: 'Planned launch',
          title: 'Time to market',
          description: 'The organization expects the work to reach users while the opportunity is still current.',
        },
        {
          label: 'Rework',
          title: 'Opportunity cost',
          description: 'Unclear priorities force extra cycles before the work can create value.',
        },
        {
          label: 'Delayed release',
          title: 'Customer momentum',
          description: 'Competitors keep moving while the team continues funding unfinished work.',
        },
      ],
    },
  },
  {
    id: 'financial-friction-bloated-infrastructure',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 3,
    title: 'Bloated Infrastructure',
    renderer: 'diagram',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Cost stack showing provision, measure, optimize, and scale intentionally',
    presenterNote: 'Frame cloud cost awareness as a principle, not personal cloud-optimization experience.',
    content: {
      renderer: 'diagram',
      title: 'More infrastructure is not always more capability.',
      summary: 'Cloud platforms make resources easy to deploy, but convenience can hide waste. Oversized services, duplicated environments, unused capacity, and weak cost visibility can quietly increase operating expenses.',
      variant: 'stack',
      items: [
        { label: 'Provision', description: 'Create only what the work needs.' },
        { label: 'Measure', description: 'Make usage and cost visible.' },
        { label: 'Optimize', description: 'Remove waste before it becomes normal.' },
        { label: 'Scale intentionally', description: 'Grow infrastructure because demand requires it.' },
      ],
    },
  },
  {
    id: 'financial-friction-risk-liability',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 4,
    title: 'Risk and Liability',
    renderer: 'diagram',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Risk matrix categories including likelihood, impact, operational dependency, and customer exposure',
    presenterNote: 'Avoid suggesting the portfolio firewall is enterprise protection.',
    content: {
      renderer: 'diagram',
      title: 'Compliance is not the same as understanding risk.',
      summary: 'Security controls matter most when they protect the operations, data, reputation, and customers the organization actually depends on. A checklist can confirm activity. It cannot replace business context or sound judgment.',
      variant: 'risk',
      items: [
        { label: 'Likelihood', description: 'How plausible is the event?' },
        { label: 'Impact', description: 'What would the business lose or need to recover?' },
        { label: 'Operational Dependency', description: 'Which workflows depend on the system?' },
        { label: 'Customer Exposure', description: 'Who could be affected outside the organization?' },
      ],
    },
  },
  {
    id: 'financial-friction-vacuum',
    chapterId: 'financial-friction',
    chapterNumber: 2,
    stageNumber: 5,
    title: 'Technology Does Not Exist in a Vacuum',
    renderer: 'image-text',
    typographyTheme: 'financial',
    visualTheme: 'financial-friction',
    transition: 'image',
    transitionScope: 'build',
    buildMode: 'replace',
    imageAssetId: 'sharks',
    ariaLabel: 'Minimal photographic stage stating that technical friction is a business cost',
    presenterNote: 'Pause before moving from consequence to strategic response.',
    chapterEnd: true,
    content: {
      renderer: 'image-text',
      headline: 'Technology does not exist in a vacuum.',
      body: 'Every line of code, server instance, workflow, and security decision has a financial and strategic consequence.',
      closingLine: 'Technical friction is a business cost.',
      layout: 'image-background',
    },
  },
  {
    id: 'blue-ocean-red-ocean',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 1,
    title: 'The Red Ocean',
    renderer: 'split',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'image',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Split stage explaining crowded markets and repeated comparison',
    presenterNote: 'Do not insult traditional candidates or existing credentials.',
    chapterStart: true,
    content: {
      renderer: 'split',
      summary: 'Crowded markets reward comparison.',
      leftTitle: 'Same capabilities',
      leftBody: 'When everyone presents similar skills in similar ways, attention shifts to credentials, price, and tiny differences.',
      rightTitle: 'Inherited boundaries',
      rightBody: 'Candidates, products, and organizations can end up competing inside a structure they did not create.',
      bridgeLabel: 'Red Ocean',
    },
  },
  {
    id: 'blue-ocean-differentiation',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 2,
    title: 'Differentiation Over Imitation',
    renderer: 'image-text',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'image',
    transitionScope: 'build',
    buildMode: 'replace',
    imageAssetId: 'sunlight',
    ariaLabel: 'Photographic stage introducing differentiation over imitation',
    presenterNote: 'Introduce Blue Ocean Strategy as a lens, not a slogan.',
    content: {
      renderer: 'image-text',
      headline: 'The alternative is not to compete louder.',
      secondaryLine: 'It is to create a more useful combination.',
      body: 'Blue Ocean Strategy asks where new value can be created rather than how existing competition can be copied. For a developing professional, that means building a perspective shaped by multiple connected disciplines.',
      layout: 'image-background',
    },
  },
  {
    id: 'blue-ocean-business-strategy',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 3,
    title: 'Business Strategy',
    renderer: 'diagram',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Layered model beginning with business strategy',
    presenterNote: 'First layer of the multidisciplinary model.',
    content: {
      renderer: 'diagram',
      title: 'Business Strategy',
      summary: 'Business provides the reason behind the work: who it serves, what outcome matters, and how success will be measured.',
      variant: 'layered',
      items: [
        { label: 'Customer value', description: 'Who benefits, and why?' },
        { label: 'Operations', description: 'How does the work fit into real workflows?' },
        { label: 'Financial awareness', description: 'What cost, return, or tradeoff matters?' },
        { label: 'Market positioning', description: 'How does the work create distinction?' },
        { label: 'Decision-making', description: 'What choice becomes clearer?' },
      ],
    },
  },
  {
    id: 'blue-ocean-artificial-intelligence',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 4,
    title: 'Artificial Intelligence',
    renderer: 'diagram',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Layered model adding artificial intelligence to business strategy',
    presenterNote: 'Emphasize direction, review, and responsible use.',
    content: {
      renderer: 'diagram',
      title: 'Artificial Intelligence',
      summary: 'AI can increase speed and expand what one person can explore. Its value depends on clear direction, critical review, and responsible use.',
      variant: 'layered',
      items: [
        { label: 'Business Strategy', description: 'Customer value, operations, financial awareness, positioning, and decisions.' },
        { label: 'Research acceleration', description: 'Move through source material and options more quickly.' },
        { label: 'Rapid prototyping', description: 'Turn product direction into testable interfaces faster.' },
        { label: 'Automation', description: 'Reduce repetitive work when the task is clearly defined.' },
        { label: 'Decision support', description: 'Help compare paths without replacing judgment.' },
        { label: 'Creative iteration', description: 'Explore variations, then critique the result.' },
      ],
    },
  },
  {
    id: 'blue-ocean-cybersecurity',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 5,
    title: 'Cybersecurity',
    renderer: 'diagram',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Layered model adding cybersecurity to business strategy and AI',
    presenterNote: 'Present security as risk-aware thinking, not an expert claim.',
    content: {
      renderer: 'diagram',
      title: 'Cybersecurity',
      summary: 'Security introduces a necessary question: can the system create value without placing the organization or its users at unacceptable risk?',
      variant: 'layered',
      items: [
        { label: 'Business Strategy', description: 'Value, operations, cost, positioning, and decisions.' },
        { label: 'Artificial Intelligence', description: 'Research, prototyping, automation, decision support, and iteration.' },
        { label: 'Risk', description: 'What could go wrong, and how likely is it?' },
        { label: 'Trust', description: 'What must users and stakeholders believe about the system?' },
        { label: 'Resilience', description: 'How does the system recover?' },
        { label: 'Data protection', description: 'What information deserves special care?' },
        { label: 'Continuity', description: 'What must keep working?' },
      ],
    },
  },
  {
    id: 'blue-ocean-product-execution',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 6,
    title: 'Software and Product Execution',
    renderer: 'diagram',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Layered model adding software and product execution to the multidisciplinary stack',
    presenterNote: 'Frame this around product direction and AI-assisted implementation.',
    content: {
      renderer: 'diagram',
      title: 'Software and Product Execution',
      summary: 'Ideas become meaningful only when they are translated into something people can use, evaluate, and improve.',
      variant: 'layered',
      items: [
        { label: 'Business Strategy', description: 'The reason behind the work.' },
        { label: 'Artificial Intelligence', description: 'The acceleration layer, guided by human direction.' },
        { label: 'Cybersecurity', description: 'The risk and trust lens.' },
        { label: 'Requirements', description: 'What the product needs to do.' },
        { label: 'User experience', description: 'How people understand and move through it.' },
        { label: 'Iteration', description: 'How feedback changes the next version.' },
        { label: 'Testing', description: 'How weak points become visible.' },
        { label: 'Delivery', description: 'How the idea becomes usable.' },
      ],
    },
  },
  {
    id: 'blue-ocean-unified-model',
    chapterId: 'blue-ocean',
    chapterNumber: 3,
    stageNumber: 7,
    title: 'The Unified Model',
    renderer: 'diagram',
    typographyTheme: 'ocean',
    visualTheme: 'blue-ocean',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    imageAssetId: 'sunlight',
    ariaLabel: 'Unified model connecting business, AI, cybersecurity, and product development around strategy, technology, and execution',
    presenterNote: 'Make the humility explicit: this is a direction, not a mastery claim.',
    chapterEnd: true,
    content: {
      renderer: 'diagram',
      title: 'The advantage is not knowing everything.',
      summary: 'It is understanding how the pieces influence one another.',
      variant: 'layered',
      items: [
        { label: 'Business', description: 'Value, operations, financial awareness, and positioning.' },
        { label: 'AI', description: 'Acceleration, exploration, prototyping, and critique.' },
        { label: 'Cybersecurity', description: 'Risk, trust, resilience, data protection, and continuity.' },
        { label: 'Product Development', description: 'Requirements, experience, iteration, testing, and delivery.' },
        { label: 'Strategy + Technology + Execution', description: 'A wider view of value, risk, users, and tradeoffs.' },
      ],
      closingLine: 'The next chapter is the experiment.',
    },
  },
  {
    id: 'living-proof-why-build',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 1,
    title: 'Why Build Jack OS?',
    renderer: 'image-text',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'reveal',
    transitionScope: 'chapter',
    buildMode: 'replace',
    imageAssetId: 'school-of-fish',
    ariaLabel: 'Jack OS case study explaining why an interactive desktop portfolio was built',
    presenterNote: 'Begin the evidence chapter through product intent.',
    chapterStart: true,
    content: {
      renderer: 'image-text',
      headline: 'A traditional resume could list the story.',
      secondaryLine: 'Jack OS could let people experience it.',
      body: 'The project began as an attempt to create a digital identity that felt personal, interactive, and memorable. Instead of placing information on another static page, the portfolio became a desktop environment visitors could explore.',
      labels: ['Identity', 'Interaction', 'Storytelling', 'Accessibility'],
      layout: 'image-right',
    },
  },
  {
    id: 'living-proof-initial-sprint',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 2,
    title: 'The Initial Sprint',
    renderer: 'terminal',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Initial sprint described as AI-assisted implementation with human-directed product vision and testing',
    presenterNote: 'State speed truthfully without turning it into a boast.',
    content: {
      renderer: 'terminal',
      title: 'The initial public version moved from concept to deployment within days.',
      lines: [
        'concept: original desktop portfolio identity',
        'direction: detailed product requirements and visual guidance',
        'implementation: AI-assisted development workflow',
        'review: human testing, critique, and release decisions',
      ],
      footer: 'AI-assisted implementation. Human-directed product vision and testing.',
    },
  },
  {
    id: 'living-proof-v1',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 3,
    title: 'Jack OS V1',
    renderer: 'timeline',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Jack OS history timeline showing V1 desktop foundation',
    presenterNote: 'Begin the release history accumulation.',
    content: {
      renderer: 'timeline',
      title: 'V1 — The Desktop',
      milestones: [
        {
          label: 'V1',
          title: 'The desktop idea becomes real.',
          description: 'Retro Macintosh-inspired identity, application icons, movable windows, project access, resume access, and early portfolio structure established the central interface.',
        },
      ],
    },
  },
  {
    id: 'living-proof-v2',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 4,
    title: 'Jack OS V2',
    renderer: 'timeline',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Jack OS history timeline adding V2 system behavior and Network Firewall update series',
    presenterNote: 'Correctly place Network Firewall in the V2 update series.',
    content: {
      renderer: 'timeline',
      title: 'V2 — The System',
      milestones: [
        {
          label: 'V1',
          title: 'The Desktop',
          description: 'Professional information could be explored as an operating system rather than read as a conventional portfolio page.',
        },
        {
          label: 'V2',
          title: 'The System',
          description: 'Custom wallpapers, personalization, widgets, motion, sound, Network Firewall, and broader system behavior made the environment more convincing.',
        },
      ],
    },
  },
  {
    id: 'living-proof-v3a',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 5,
    title: 'Jack OS V3A',
    renderer: 'timeline',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'slide',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Jack OS history timeline adding V3A Identity Update',
    presenterNote: 'V3A is the Identity Update, not a cybersecurity update.',
    content: {
      renderer: 'timeline',
      title: 'V3A — The Identity Update',
      milestones: [
        {
          label: 'V1',
          title: 'The Desktop',
          description: 'The operating-system metaphor became the primary navigation model.',
        },
        {
          label: 'V2',
          title: 'The System',
          description: 'Personalization, system interaction, sound, and the Network Firewall update series expanded the experience.',
        },
        {
          label: 'V3A',
          title: 'The Identity Update',
          description: 'Custom application artwork, About Me identity, Road Map, Achievements, system metrics, Simple Mode, recruiter entry paths, wallpapers, and branding clarified the message.',
        },
      ],
    },
  },
  {
    id: 'living-proof-ai-assisted-workflow',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 6,
    title: 'The AI-Assisted Workflow',
    renderer: 'diagram',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Process diagram explaining AI-assisted implementation and human-directed product decisions',
    presenterNote: 'Key transparency stage. Honest, direct, not apologetic.',
    content: {
      renderer: 'diagram',
      title: 'The implementation was accelerated by AI. The direction was not automated.',
      summary: 'The project was developed through detailed prompting, visual direction, product prioritization, repeated testing, and corrective feedback. AI generated much of the code, while product decisions, experience design, feature selection, and quality review remained intentionally directed.',
      variant: 'flow',
      items: [
        { label: 'Idea', description: 'Define the product concept and purpose.' },
        { label: 'Specification', description: 'Write detailed requirements and visual direction.' },
        { label: 'AI Implementation', description: 'Use Codex and related tools to produce code.' },
        { label: 'Testing', description: 'Evaluate the experience directly.' },
        { label: 'Critique', description: 'Identify what feels wrong or unclear.' },
        { label: 'Revision', description: 'Direct focused changes.' },
        { label: 'Release', description: 'Ship the improved version.' },
      ],
    },
  },
  {
    id: 'living-proof-continuous-improvement',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 7,
    title: 'Continuous Improvement',
    renderer: 'diagram',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'accumulate',
    ariaLabel: 'Feedback loop showing observe, identify, specify, revise, validate, and release',
    presenterNote: 'Show that weaknesses became roadmap inputs.',
    content: {
      renderer: 'diagram',
      title: 'Shipping was not the finish line.',
      summary: 'Each release exposed new problems: crowded icon layouts, inaccessible entry points, inconsistent artwork, unclear information hierarchy, and features that needed stronger purpose. Those weaknesses became the roadmap for the next version.',
      variant: 'loop',
      items: [
        { label: 'Observe', description: 'Use the product and notice friction.' },
        { label: 'Identify', description: 'Name what is confusing, weak, or crowded.' },
        { label: 'Specify', description: 'Turn the issue into clear requirements.' },
        { label: 'Revise', description: 'Direct the next implementation pass.' },
        { label: 'Validate', description: 'Test the result against the goal.' },
        { label: 'Release', description: 'Move the improved system forward.' },
      ],
    },
  },
  {
    id: 'living-proof-current-result',
    chapterId: 'living-proof',
    chapterNumber: 4,
    stageNumber: 8,
    title: 'The Current Result',
    renderer: 'quote',
    typographyTheme: 'documentary',
    visualTheme: 'living-proof',
    transition: 'fade',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Chapter 4 conclusion stating that Jack OS is proof of follow-through, not perfection',
    presenterNote: 'Let the work carry the conclusion.',
    chapterEnd: true,
    content: {
      renderer: 'quote',
      quote: 'A portfolio became a product platform.',
      body: 'Jack OS now combines professional history, projects, credentials, recruiter tools, cybersecurity demonstrations, personalization, system behavior, and this keynote inside one evolving experience.',
      lines: [
        'The result is not proof of perfection.',
        'It is proof of follow-through.',
        'The work remains in progress by design.',
      ],
    },
  },
  {
    id: 'simplicity-clear-over-complicated',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 1,
    title: 'Clear Over Complicated',
    renderer: 'split',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'fade',
    transitionScope: 'chapter',
    buildMode: 'replace',
    ariaLabel: 'Before and after comparison of more information versus clearer understanding',
    presenterNote: 'Begin simplifying the canvas.',
    chapterStart: true,
    content: {
      renderer: 'split',
      summary: 'Complexity is not the same as sophistication.',
      leftTitle: 'More information',
      leftBody: 'A system can contain impressive detail and still fail the people expected to use it.',
      rightTitle: 'Clearer understanding',
      rightBody: 'The final measure is whether the design makes the right action, decision, or idea easier to understand.',
      bridgeLabel: 'Clarity',
    },
  },
  {
    id: 'simplicity-execution-speaks',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 2,
    title: 'Execution Speaks Louder Than Noise',
    renderer: 'image-text',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'image',
    transitionScope: 'build',
    buildMode: 'replace',
    imageAssetId: 'ocean-floor',
    ariaLabel: 'Minimal image stage explaining that visible work creates evidence',
    presenterNote: 'Connect directly back to the Jack OS evidence chapter.',
    content: {
      renderer: 'image-text',
      headline: 'Execution speaks louder than noise.',
      body: 'A strong idea does not need exaggerated language when the work is visible. Clear reasoning, honest constraints, and continuous improvement create their own evidence.',
      layout: 'image-left',
    },
  },
  {
    id: 'simplicity-manifesto',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 3,
    title: 'The Manifesto',
    renderer: 'quote',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Manifesto stage quoting simplicity as the ultimate sophistication without attribution',
    presenterNote: 'Do not attribute the disputed phrase.',
    content: {
      renderer: 'quote',
      quote: 'Simplicity is the ultimate sophistication.',
      body: 'Make complex systems understandable through thoughtful design, clear communication, and real work.',
      lines: ['This is the permanent North Star.'],
    },
  },
  {
    id: 'simplicity-system-status',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 4,
    title: 'System Status: Online',
    renderer: 'terminal',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'fade',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Macintosh-inspired status display showing strategy connected, execution active, and learning continuous',
    presenterNote: 'Keep this calm and restrained.',
    content: {
      renderer: 'terminal',
      title: 'SYSTEM STATUS: ONLINE',
      lines: [
        'STRATEGY: CONNECTED',
        'EXECUTION: ACTIVE',
        'LEARNING: CONTINUOUS',
      ],
      footer: 'The system remains unfinished. So does the journey.',
    },
  },
  {
    id: 'simplicity-power-down',
    chapterId: 'simplicity',
    chapterNumber: 5,
    stageNumber: 5,
    title: 'Power Down Keynote',
    renderer: 'terminal',
    typographyTheme: 'minimal',
    visualTheme: 'simplicity',
    transition: 'reveal',
    transitionScope: 'build',
    buildMode: 'replace',
    ariaLabel: 'Final keynote stage ready to return to Jack OS',
    presenterNote: 'Power Down Keynote closes the window through the Jack OS window manager.',
    chapterEnd: true,
    completionAction: 'power-down',
    content: {
      renderer: 'terminal',
      title: 'Power Down Keynote',
      lines: [
        'presentation: complete',
        'desktop: waiting',
        'next action: return to Jack OS',
      ],
      footer: 'Thank you for watching.',
    },
  },
]

export function getKeynoteStepById(stepId: string) {
  return KEYNOTE_STEPS.find((step) => step.id === stepId)
}

export function getKeynoteStepIndexById(stepId: string) {
  return KEYNOTE_STEPS.findIndex((step) => step.id === stepId)
}
