export const SEARCH_ALIASES: Record<string, readonly string[]> = {
  'app:resume': ['cv', 'curriculum vitae'],
  'app:kickoff': ['football', 'nfl', 'prediction', 'sports'],
  'app:pocket-pier': ['game', 'fishing', 'harbor', 'godot', 'ios', 'gdscript'],
  'app:blue-ocean': ['keynote', 'presentation', '1984', 'strategy'],
  'app:portfolio': ['overview', 'work'],
  'app:wallpapers': ['personalize', 'background', 'wallpaper'],
  'app:certifications': ['certs', 'certificate', 'badge'],
  'app:assistant': ['jd', 'j.d.', 'help'],
  'app:home': ['welcome', 'start'],
  'app:recruiter': ['hiring', 'recruiter', 'overview'],
  'project:jackos': ['os', 'operating system', 'jack os', 'desktop'],
  'project:kickoff': ['football', 'nfl', 'prediction'],
  'project:pocket-pier': ['game', 'godot', 'ios', 'harbor'],
  'project:blue-ocean': ['keynote', '1984', 'presentation'],
  'case-study:jackos': ['operating system', 'jack os'],
  'case-study:kickoff': ['football', 'prediction'],
  'case-study:pocket-pier': ['game', 'godot'],
  'case-study:blue-ocean': ['keynote', '1984'],
  'system:personalize': ['wallpaper', 'background', 'personalize'],
  'system:toggle-theme': ['theme', 'dark mode', 'light mode', 'dark', 'light'],
  'system:reset-layout': ['reset layout', 'window layout'],
  'system:restart': ['reload', 'reboot'],
  'system:simple-mode': ['simple', 'plain portfolio'],
  'system:copy-email': ['email', 'contact', 'gmail'],
  'system:ask-jd': ['assistant', 'jd', 'help'],
}

export const FIREWALL_SEARCH_TERMS = [
  'allow vs block',
  'inbound and outbound',
  'ports and protocols',
  'rule priority',
  'sample network traffic',
  'beginner guide',
  'packet inspector',
  'firewall certified',
] as const
